### ISSUE TITLE
Add method to disable strict service name checking.

### ISSUE THREAD

**Issue by natedogith1** [python-zeroconf/python-zeroconf#1046]
There's no way to specify that invalid names should be allowed when registering a service.  I'm trying to register a service of "_oculusal_sp._tcp.local." (which is what the oculus quest 2 uses for airlinking), but I get an BadTypeInNameException error.  For now I have a monkey-fix workaround of
```python
zeroconf.service_type_name.__kwdefaults__['strict'] = False
```

**Comment by azogue** [comment]
BTW, my use case is similar: I'm using `zeroconf` to work with a fixed [German protocol for communications](https://www.vdv.de/ip-kom-oev.aspx) (part of VDV301/ IBIS-IP [standards](https://www.vdv.de/301-2ses.pdfx?forced=false)) inside **trains** 🚂, where all devices expose different mDNS services and XML APIs to find themselves and talk between them. 

The thing is that services have names like `"CustomerInformationService-F4D4895E9EEB._ibisip_http.local."` or `"DeviceManagementService-1A77306416A9._ibisip_http.local."`, which don't follow the 'strict' convention, and raise the  `BadTypeInNameException` 🥲

As the _hack_ to disable the 'strict' mode is getting harder 😆, maybe we should **find a better place to expose this option?** 🙏

I know the goal of the library is to follow the standard, as it should be, but I am also a realist who has to deal everyday with legacy systems or imperfect standards, with no way to bypass them 🥲

I've been following the quick pace in latest releases, and all the work that @bdraco is putting in (thanks a lot!!), so I suspect this issue is not considered important enough (or it would be fixed by now 😅). 

I offer to help, and make a PR to expose this strict-mode deactivation, but I would need directions on where and how to expose it 🥺

**Comment by bdraco** [comment]
Happy to take a pr to add it as a kwarg where you register the service. Not sure what your code looks like to do that so I can't specifically suggest the entry point though. 

I would start with a PR with abasic test and we can move it to a better location if needed.

**Comment by azogue** [comment]
> Happy to take a pr to add it as a kwarg where you register the service

I've just reviewing the usages and it seems easy, just adding the kwarg in `async_register_service`, `register_service`, `instance_name_from_service_info`, `ServiceBrowser` and `AsyncServiceBrowser`. I'll try to make that PR 👍
