### ISSUE TITLE
Unexpected multicast response

### ISSUE THREAD

**Issue by polakovicp** [python-zeroconf/python-zeroconf#1096]
I have a setup with C++ client and Python service using zeroconf==0.37.0 (python3.6).
My C++ client's probing for service on all interfaces and every request is marked as Unicast response. Maybe I am missing something, but why is Python service responding to multicast address 224.0.0.251 and only one response actually goes to interface address (192.168.56.1)?
![image](https://user-images.githubusercontent.com/522894/195891004-fc47af2b-2c66-4d0a-b9dc-638f7f9f46d6.png)

I'd expect also no multicast response in this case.
Thank you for clarification

**Comment by bdraco** [comment]
[5.4](https://www.rfc-editor.org/rfc/rfc6762#section-5.4).  Questions Requesting Unicast Responses

When receiving a question with the unicast-response bit set, a
   responder SHOULD usually respond with a unicast packet directed back
   to the querier.  However, if the responder has not multicast that
   record recently (within one quarter of its TTL), then the responder
   SHOULD instead multicast the response so as to keep all the peer
   caches up to date, and to permit passive conflict detection.  In the
   case of answering a probe question ([Section 8.1](https://www.rfc-editor.org/rfc/rfc6762#section-8.1)) with the unicast-
   response bit set, the responder should always generate the requested
   unicast response, but it may also send a multicast announcement if
   the time since the last multicast announcement of that record is more
   than a quarter of its TTL.

I think the above is the behavior you are seeing
